### ISSUE TITLE
sql) song 테이블에서 PK를 songNo로 변환

### ISSUE THREAD

**Issue by mome0320** [taikowiki/taikowiki-svelte#114]
songNo 컬럼 값은 동더히로바 페이지에서 따오는 거기도 하고
고유하며 null 값이 될 수 없을 거 같은 데
그냥 songNo를 int형으로 변환하고 order를 삭제 하고
SongNo를 PK로 지정해도 상관 없지 않나라는 생각이 듭니다.

애초에 저 열을 많이 사용하니까 색인을 시키는 게 좋을 거 같습니다.

**Comment by mome0320** [comment]
Pr하기에는 직접 db 직업도 수행해야하는 번거로움이 있어 제안 드립니다.

**Comment by mome0320** [comment]
PR로 수정하기에는 소스 상에서의 덤프 쪽에 알려지지 않은 SQL 구조가 존재해서 건들 영역이 아닌 거 같아 요청 드립니다.

**Comment by hotsixman** [comment]
콘솔한정곡의 경우 int형으로 사용하지 않고 `NS2_1` 과 같이 사용할 예정이라 text형으로 계속 사용해야 할 듯 합니다
