### ISSUE TITLE
DiffchartSongPc resizeTitle 기능 대체방안

### ISSUE THREAD

**Issue by kecan0406** [taikowiki/taikowiki-svelte#196]
DiffchartSongPc 컴포넌트의 resizeTitle 함수가 성능저하를 발생시키는 것 같습니다
이 함수는 곡의 정보를 나타내는 컴포넌트의 텍스트가 차지하는 공간에 비례해 font-size를 동적으로 변환 시키는 목적으로 사용되며,
초기 페이지 렌더링, viewport 크기 조정시에 각 컴포넌트마다 실행되어 성능저하가 발생합니다.

해당 사항을 CSS에서 해결해보고자 찾아봤으나 font-size를 부모 Element 크기를 전부 채우도록 하는 기능은 없습니다.

resizeTitle 함수를 대체할만한 방법이나 다른 방안을 찾는 것이 좋을 것 같습니다.

| resizeTitle 유지 | resizeTitle 제거 |
|--------|--------|
| ![{92FCE28B-7B10-4F32-B803-CA6F146B3467}](https://github.com/user-attachments/assets/30ff2d99-093c-4f69-82ef-8ac648e1fd15)| ![{86AA68FF-619A-4583-8405-C9EB3D877627}](https://github.com/user-attachments/assets/8e3603ed-baff-4113-8b1d-61552c775bc2) |

**Comment by hotsixman** [comment]
꽉 맞게 하지 않는다면 해결할 수 있긴 하겠지만

꽉 맞게 하려면 제목이 렌더링 됐을 때의 길이를 미리 계산해서 적절한 font-size를 구하는 게 괜찮을 것 같아요.
예를 들어 영어 대문자 / 영어 소문자 / 숫자 / !, *같은 얇은 문자 / 한자와 가나 이런 식으로 나눠서 미리 계산해 보고 적절한 크기를 구해서 렌더링하면 괜찮지 않을 까 싶습니다.

성능 이슈가 있긴 한데 사용할 때 그렇게 심한 것 같지 않아서 당분간은 놔두려고 합니다.
