### ISSUE TITLE
[Proposal] 서열표 페이지 개선안

### ISSUE THREAD

**Issue by exqt** [taikowiki/taikowiki-svelte#250]
![image](https://github.com/user-attachments/assets/95747370-fbe5-464e-937a-604ccd5cc8d1)

1. 서열표에 (쌍타, 아시아밴, 현인/보통) 보면 숨기기 기능 
  - 추가로 왕관 조건으로 숨기기 : 예시) 클리어 서열표에서 이미 클리어 한건 제외하고 보고 싶음
2. 헤더 접기 기능 (예전 위키에서는 있는데 지금은 사라진듯?)
3. (클리어 개수 / 전체 개수) 로 표시, 풀콤 서열표에선 (풀콤 개수 / 전체 개수) 로 표시

검토해보시고 넣어도 되는거 알려주심 감사
구현은 바쁘시면 저한테 배정해 주세요

**Comment by hotsixman** [comment]
1. 보류
2. 확인
3. 보류
