### ISSUE TITLE
Romaji translation for song titles

### ISSUE THREAD

**Issue by Leuphorie** [taikowiki/taikowiki-svelte#292]
Hi all, 

I think this change would be of great benefit for overseas players. 

Example:
束ね糸 becomes Tabaneito
FooFooカセット becomes FooFoo Casette
etc...

It would fit in this context menu on the website:
![image](https://github.com/user-attachments/assets/729defaf-4602-4335-80a2-adbc783fc332)

Thank you

**Comment by hotsixman** [comment]
That's a good idea.

**Comment by hotsixman** [comment]
It will start after the Svelte 5 migration

**Comment by Leuphorie** [comment]
Thank you. I am looking forward to it.

**Comment by hotsixman** [comment]
The feature has been added, but we don't have Romaji data for some songs.
We will add them later, but you can submit Romaji data to us here.
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/28450caa-ac5f-42dc-8f57-c0b6848178b8" />

**Comment by hotsixman** [comment]
![image](https://github.com/user-attachments/assets/871f6455-6b82-421d-bd04-a7d9c2565480)
![image](https://github.com/user-attachments/assets/10ecf407-e0f0-4c90-a155-ad61c6d0b74a)

**Comment by Leuphorie** [comment]
It might be worth cross-checking with "Every Song Ever", a large-scale 太鼓の達人 TJA song and chart archive in English.

https://ese.tjadataba.se/ESE/ESE

**Comment by hotsixman** [comment]
> It might be worth cross-checking with "Every Song Ever", a large-scale 太鼓の達人 TJA song and chart archive in English.
> 
> https://ese.tjadataba.se/ESE/ESE

Thanks!
But since there are so many songs and we need to distinguish between Romajis and unofficial English titles, so it will take a long time.

**Comment by Leuphorie** [comment]
I understand. I plan to help with adding song titles little by little.
