### ISSUE TITLE
계정별 언어설정 저장

### ISSUE THREAD

**Issue by SayakoTchi** [taikowiki/taikowiki-svelte#36]
현
언어설정후 새로고침하면 언어설정이 초기화됨
후
언어설정을 계정별로 저장후, 설정지속

**Comment by alphaorderly** [comment]
언어는 비로그인인 경우도 있으니 로컬스토리지를 이용하는것도 괜찮다고 생각합니다.

**Comment by hotsixman** [comment]
분명 로컬스토리지를 넣었던 것 같은데 빠진 것 같네요 ㅠㅠ

`로컬 스토리지 ?? 계정 저장 언어 ?? ko`로 할 생각입니다.

**Comment by hotsixman** [comment]
#108
