### ISSUE TITLE
난이도 레이아웃 조정

### ISSUE THREAD

**Issue by SayakoTchi** [taikowiki/taikowiki-svelte#65]
![bugs1](https://github.com/taikowiki/taikowiki-svelte/assets/33560035/91263b19-7188-4127-8302-cccc20428568)
![bugs2](https://github.com/taikowiki/taikowiki-svelte/assets/33560035/be149728-f76f-4b48-b3ff-3ebf2ba72d9b)

**Comment by hotsixman** [comment]
확인
