### ISSUE TITLE
디자인 시안 その1

### ISSUE THREAD

**Issue by Stoxsh** [taikowiki/taikowiki-svelte#69]
### 서열표 레이아웃 살짝 변경
여기서
![from](https://github.com/taikowiki/taikowiki-svelte/assets/14972741/7a44103c-c43a-458b-bcc6-349bd423ab90)
이걸로
![to](https://github.com/taikowiki/taikowiki-svelte/assets/14972741/07064b61-323b-4c63-a6c9-61953077f348)

### ios 및 다른 디바이스 파비콘도 추가
<img width="257" alt="Screenshot 2024-06-04 at 4 22 55 PM" src="https://github.com/taikowiki/taikowiki-svelte/assets/14972741/a8c995d4-6b27-48d0-9d8a-0ac865322362">

**Comment by Stoxsh** [comment]
허가시 바로 풀리퀘

**Comment by hotsixman** [comment]
모바일이 어떻게 바뀌는 지도 보여주실 수 있는 지

**Comment by hotsixman** [comment]
자작 서열표 기능을 위해 기존 서열표의 윗부분이 색을 바꿀 수 있게 했는데, 그 부분이 어떻게 처리되었는지도 궁금합니다.

**Comment by mome0320** [comment]
어차피 PR 올려도 검토 후에 거절(close) 할 수도 있으니까
그냥 PR 올리셔도 상관 없을 거 같습니다.

PR 올리고 거기서 토론해도 좋을 거 같은데용.

**Comment by hotsixman** [comment]
pr 해주시면 감사하겠습니다

**Comment by hotsixman** [comment]
#77

**Comment by hotsixman** [comment]
#77
