### ISSUE TITLE
메인 페이지 추가

### ISSUE THREAD

**Issue by mome0320** [taikowiki/taikowiki-svelte#74]
메인 페이지가 아직 제공이 되지 않아 불편을 느낄 수 있습니다.
혹시 메인 페이지는 추가할 의향이 있을까 질문 드립니다.

없으시면 그냥 메인 페이지에 song 탭으로 가지게 하면 될 거 같네요!

**Comment by hotsixman** [comment]
메인페이지를 추가할 의향은 있으나 아직 들어갈 컨텐츠가 정해지지 않아서... 우선 지금은 song으로 리다이렉트하는게 좋은 것 같네요.
