### ISSUE TITLE
DB 쿼리 데이터 더미 샘플 또는 DB 템플릿 구조 안내 필요

### ISSUE THREAD

**Issue by mome0320** [taikowiki/taikowiki-svelte#78]
제 입장에선 곡 정보가 없다 보니까
테스트를 하려면 더미데이터 넣어 테스트해봐야하는 데

우선 덤프 DB만으론 데이터 구조를 한눈에 보기가 어렵습니다.
물론 소스 일일이 찾아서 typescript로 정의 된 것으로 간접적으로 찾아보면 되긴하나

예를 들어 대충 구조를 보니 diffchart 쪽 data에 약간 몰빵된 느낌이 있어서 말이져
혹시 이와 관련해서 약간 가이드라인 잡아 주실 수 있으신가요?

**Comment by hotsixman** [comment]
song 테이블의 courses 열과 diffchart 테이블의 data 컬럼이 json 형식으로 되어있습니다. 추후에 sql 디렉토리에 관련 내용을 추가하도록 하겠습니다. 일단 diffchart와 song데이터 및 다른 테이블 구조가 담긴 sql 파일 올려드릴게요.

env 파일 형식도 추후에 파일로 추가하도록 하겠습니다.
우선 이걸 사용해주세요.
```env
DB_HOST = 
DB_DATABASE = 
DB_USER = 
DB_PASSWORD = 
#mysql 써서 mysql로 적어야 함
DB_SERVICE = mysql

#32바이트 값을 hex로 표현한 값
#require('crypto').randomBytes(32).toString('hex') 해서 만들 수 있음
#유저 데이터가 닮긴 쿠키 값을 암호화/복호화 하는 데 사용됨
AUTH_KEY = 

#github oauth용 (로그인 안쓸거면 안넣어도 됨)
GITHUB_CLIENT_ID = 
GITHUB_CLIENT_SECRET = 

#kakao oauth용 (로그인 안쓸거면 안넣어도 됨)
KAKAO_CLIENT_ID = 
KAKAO_CLIENT_SECRET = 
```

**Comment by hotsixman** [comment]
[taikowiki.txt](https://github.com/user-attachments/files/15633869/taikowiki.txt)
`.sql` 파일로 바꿔서 사용해주세용

**Comment by mome0320** [comment]
확인했습니다. 감사합니다!
