### ISSUE TITLE
페이지 제목 디테일 추가

### ISSUE THREAD

**Issue by exqt** [taikowiki/taikowiki-svelte#79]
![image](https://github.com/taikowiki/taikowiki-svelte/assets/8168124/979de0ee-42ab-4179-bfa5-e1d7afc76c8d)

현재 html title이 모두 동일하여 페이지 구분이 안됩니다.

```svelte
<svelte:head>
    <title>태고의 달인 위키 - 곡 정보 {songName}</title> 
</svelte:head>
```

이런식으로 해주시면 더 좋을거 같아요

**Comment by mome0320** [comment]
추가적인 의견을 덧붙이자면

곡 - {songname} | 태고의 달인 위키
단위도장 | 태고의 달인 위키
서열표 - ★10 | 태고의 달인 위키
이런 느낌이 은근 괜찮을 거 같아

이런식으로 템플릿으로 구성하는 게 좋아보입니다.
{상위 메뉴} - {하위 매뉴} | 홈페이지 제목

**Comment by hotsixman** [comment]
추가 예정입니다. 임시로 넣어둔거라 나중에 바꿀 예정이에요
