### ISSUE TITLE
디자인 시안 その2 (곡 정보)

### ISSUE THREAD

**Issue by mome0320** [taikowiki/taikowiki-svelte#81]
![image](https://github.com/taikowiki/taikowiki-svelte/assets/18746638/5ecd9d6a-292d-419a-93b5-a500bdaac69c)
프로젝트로 이슈 관리 하시길레 이슈 올리고 바로 PR 올리겠습니다.
밑에는 귀찮아서 다른 사람이 해주시면 감사요.

**Comment by hotsixman** [comment]
1. 수정 요청 버튼 모서리와 dayjs를 사용하여 날짜를 표현하는 것은 좋은 것 같습니다.
2. 번역명은 한번에 여러 제목을 볼 수 있게 하기 위해 곡 검색 페이지와 같은 방식을 일부러 사용하지 않았습니다.
3. SongDataDisplay의 경우 내용의 길이가 짧으면 한 줄로 예쁘게 나오기 때문에 기존 방식을 사용하였습니다. 
![image](https://github.com/taikowiki/taikowiki-svelte/assets/122341094/0410db7c-99b9-42f6-9713-a5bc8f273705)
다만 길이가 길어지면 못생겨지기 때문에 나중에 수정해보도록 하겠습니다.
4. SongDataDisplay에서 태그로 감싸는 건 좋은 아이디어 같습니다.

**Comment by mome0320** [comment]
> 1. 수정 요청 버튼 모서리와 dayjs를 사용하여 날짜를 표현하는 것은 좋은 것 같습니다.
> 2. 번역명은 한번에 여러 제목을 볼 수 있게 하기 위해 곡 검색 페이지와 같은 방식을 일부러 사용하지 않았습니다.
> 3. SongDataDisplay의 경우 내용의 길이가 짧으면 한 줄로 예쁘게 나오기 때문에 기존 방식을 사용하였습니다.
>    ![image](https://private-user-images.githubusercontent.com/122341094/337858616-0410db7c-99b9-42f6-9713-a5bc8f273705.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4MzMzNjgsIm5iZiI6MTcxNzgzMzA2OCwicGF0aCI6Ii8xMjIzNDEwOTQvMzM3ODU4NjE2LTA0MTBkYjdjLTk5YjktNDJmNi05NzEzLWE1YmM4ZjI3MzcwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQwNzUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTFhM2FhNzgyZjRjYzZkYzFiYzdkZWI2NWEyNjRlOTRkZGU2ZTFkOTRlYzFjZjI4NzRjZTUxZTE1OWIxZmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5TFQ2r-m3d-2k_Jlv2uuLlG3rR02nho6gDzDNgHZm4s)
>    다만 길이가 길어지면 못생겨지기 때문에 나중에 수정해보도록 하겠습니다.
> 4. SongDataDisplay에서 태그로 감싸는 건 좋은 아이디어 같습니다.
   
2. 아 번역 한번에 볼 수 있게 하는 의도인 줄은 몰랐습니다. 번거롭게 번역을 누르는 거보단 한번에 보는 게 좋을 거 같습니다
   
3. 적당히 길이 짧으면 저렇게 이쁘게 나오긴 하는 데 길게 하면...
![image](https://github.com/taikowiki/taikowiki-svelte/assets/18746638/cb188814-39c3-4fda-95eb-c4b5d5ddd0b6)   
저런 지경이 되서 ㅋㅋㅋㅋㅋ 

  그렇다고 너무 짧으면 
  ![image](https://github.com/taikowiki/taikowiki-svelte/assets/18746638/4b2c8531-937b-4f16-a0c4-edd9a2889189)
  뭔가 이상하게 정렬이 되고 이쁘지가 않아서 좌우 정렬 맞춰서 깔끔하게 해야할 거 같고

~~그리고 테이블 같은 각진 디자인은 제가 불호인지라~~
한번에 깔끔하게 하고 싶어서 제가 선호하는 디자인 양식 대로 해서 제시해본겁니다.
   
4. 확실히 쉼표 말고 저렇게 태그 씌워서 구분하는 게 가독성이 좋아보일 겁니다.

일단 PR은 유지하겠습니다 어차피 거기서 님이 수정 가능하니까   
요청하신다면 PR 제가 스스로 닫아도 되고여   

암튼 검토 및 피드백 감사합니다.

**Comment by hotsixman** [comment]
dayjs, 수정 요청 버튼 모서리, 태그 형식은 추가했습니다.

![image](https://github.com/taikowiki/taikowiki-svelte/assets/122341094/44096d47-89c4-4011-bb70-87019912b78b)
SongDataDisplay는 우선 너무 길어지면 table과 유사하게 보이도록 했습니다.
