### ISSUE TITLE
부동소수점 연산 문제로 무한소수로 나타나는 현상

### ISSUE THREAD

**Issue by mome0320** [taikowiki/taikowiki-svelte#85]
![image](https://github.com/taikowiki/taikowiki-svelte/assets/18746638/d27abafa-41a6-4867-9634-c6aafc764511)
최대 연타 시간 부동 소숫점 연산 문제로 합산 출력이 무한 소수로 나옵니다.

**Comment by hotsixman** [comment]
#58 에서 수정했습니다.
