### ISSUE TITLE
SSR 지원

### ISSUE THREAD

**Issue by hotsixman** [taikowiki/taikowiki-svelte#92]
곡 정보를 localStorage에 저장해놓고 갖다 쓰는 방식을 버리고 
필요한 곡 데이터만 db에서 불러올 수 있도록 하여 SSR이 가능하도록 만들기

**Comment by mome0320** [comment]
저는 개인적으로 기본 CSR 방식이 좋다고 봅니다.
localStorage 등 로컬 스토리지 쪽에서 저장(캐싱)하고 오프라인에서도
웹앱을 불러올 수 있게끔 제공하는 방식이 괜찮아보여서요.

자세한 제안은 #94 에서 남겨놓았습니다.

**Comment by hotsixman** [comment]
로컬스토리지에 저장하는 방식을 버리려고 하는 건 사실 트래픽 때문도 있습니다. 기존 방식은 곡 db가 업데이트 되면 모든 곡 데이터를 다시 불러와서 로컬스토리지에 저장하기때문에, 사소한 데이터 하나만 변경되어도 모든 곡 데이터를 다시 불러오기 때문에 트래픽 낭비가 심합니다. 
추후에 localStorage에 곡 데이터가 아예 없을 때만 곡 데이터를 불러와 저장하고, 이후에는 개별 song/[songNo] 페이지에 접속하면 localStorage의 데이터를 업데이트 하는 방식을 사용하면 좋을 것 같습니다.

**Comment by mome0320** [comment]
> 로컬스토리지에 저장하는 방식을 버리려고 하는 건 사실 트래픽 때문도 있습니다. 기존 방식은 곡 db가 업데이트 되면 모든 곡 데이터를 다시 불러와서 로컬스토리지에 저장하기때문에, 사소한 데이터 하나만 변경되어도 모든 곡 데이터를 다시 불러오기 때문에 트래픽 낭비가 심합니다. 
> 추후에 localStorage에 곡 데이터가 아예 없을 때만 곡 데이터를 불러와 저장하고, 이후에는 개별 song/[songNo] 페이지에 접속하면 localStorage의 데이터를 업데이트 하는 방식을 사용하면 좋을 것 같습니다. 

여기 이슈 주제에 약간 벗어난 이야기이긴 합니다만서도
그 사안에 대해 의견 내자면
트래픽 낭비는 확실히 문제점이긴 합니다.

다만 걱정되는 게 최초 시에 전체 곡 불러오기 후 만약에 클릭 시 데이터 업데이트라면 추후에 원본과 캐싱의 일관성이 떨어질 수도 있을 걸로 예상이 됩니다.

ex) 클릭 시 그 곡을 갱신 방식일 시 다수 신규 곡이 나오면 신규 곡 데이터가 갱신 안될 수도 있음.

일단 계획 초기 단계긴 하지만 구현 시
캐시 업데이트 시간 기준으로 그 후에 업데이트 된 곡 리스트로 로드하는 등에 대한 보완책이 필요할 거 같습니다.

물론 제 해결책이 그렇게 좋은 건 아니라서 다른 좋은 방법이 있으면 그런 방법으로 사용하셔도 괜찮을 거 같습니다.

**Comment by hotsixman** [comment]
#95
